// <auto-generated />
using System;
using MagicVilla_VillaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_VillaAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_VillaAPI.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "Furnished\r\nCentral A/C\r\nCovered Parking\r\nKitchen Appliances\r\nSecurity\r\nShared Gym\r\nShared Pool",
                            CreatedAt = new DateTime(2023, 2, 16, 13, 45, 58, 360, DateTimeKind.Local).AddTicks(8639),
                            Details = "Green Community is a residential community located in Dubai, United Arab Emirates. It features a variety of fully furnished 1 bedroom apartments with park views available for rent. The apartments are equipped with modern amenities and are located in a peaceful and serene setting, surrounded by lush greenery and landscaped gardens.",
                            ImageUrl = "https://www.propertyfinder.ae/en/plp/rent/apartment-for-rent-dubai-green-community-green-community-west-southwest-apartments-9327099.html",
                            Name = "GREEN COMMUNITY WEST",
                            Occupancy = 5,
                            Rate = 0.0,
                            Sqft = 900,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "Furnished\r\nCentral A/C\r\nCovered Parking\r\nKitchen Appliances\r\nSecurity\r\nShared Gym\r\nShared Pool",
                            CreatedAt = new DateTime(2023, 2, 16, 13, 45, 58, 360, DateTimeKind.Local).AddTicks(8654),
                            Details = "The Edge is nestled within the mixed-use gated community of Ewan Residences, Dubai Investment Park. This sleek, high-quality, yet affordable, residential development offers its tenants the utmost accessibility to Dubai’s most prominent business and retail centers, including the highly anticipated Expo 2020 site.",
                            ImageUrl = "https://www.propertyfinder.ae/en/plp/rent/apartment-for-rent-dubai-dubai-investment-park-the-edge-9058935.html",
                            Name = " THE EDGE,",
                            Occupancy = 4,
                            Rate = 0.0,
                            Sqft = 800,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "Unfurnished\r\nBuilt in Wardrobes\r\nChildren's Play Area\r\nCovered Parking\r\nSecurity\r\nView of Landmark",
                            CreatedAt = new DateTime(2023, 2, 16, 13, 45, 58, 360, DateTimeKind.Local).AddTicks(8656),
                            Details = "Spacious | Modern Interior | Kitchen Equipped\r\n\r\n*Ready to move in\r\n*Open and a Fully Fitted kitchen ( Oven, refrigerator & washing machine included)\r\n*Bathroom: 2\r\n*Free 4 burner cooker\r\n*Multiple Units Available\r\n\r\nFeatures:\r\n*Low-rise building\r\n*Central air conditioning\r\n*Gymnasium\r\n*24 hrs Security\r\n*Games room and children’s play area\r\n*Maintenance Included\r\n*Near to Shops\r\n*In front of Public Transportation\r\n*In front of Park\r\n\r\nSchools near by:\r\n1. Nibras International School ( [link not available] )\r\n2. Greenfield International School ( [link not available] )\r\n3. The International School of Choueifat-DIP ( [link not available] 4. Dove Green Private School ( [link not available] )\r\n5. Bright Riders School ( [link not available]\r\nLocation:\r\n*5 Min to Sheikh Mohammed Bin Zayed road\r\n*10 Mins to Al Khail Road\r\n*12 Mins to Marina, JLT , JBR\r\n*12 Mins to Ibn Battuta Mall\r\n*12 Min to Ikea\r\n*15 Min to Dubai Hills Mall\r\n*15 Mins to Mall of the Emirates\r\n*20 Mins to Dubai Mall\r\n*25 Mins to Dubai Airport\r\n\r\nDubai Investments Park is perfect location for families with easy access to main roads in Dubai. DIP is a business park area in Dubai, United Arab Emirates, including commercial, and industrial, and residential development. It is designed to be one of the most environment-friendly developments in the region.\r\n\r\nOne Tastik Real Estate Brokerage:\r\nTalent. Drive. Innovation. Service.\r\nWe have what it takes to push real estate forward!\r\n\r\n*For more details please call our Senior Property Consultant Lucy Carmichael on whatsapp\r\nDisplay phone number",
                            ImageUrl = "https://www.propertyfinder.ae/en/plp/rent/apartment-for-rent-dubai-dubai-investment-park-darwish-bin-ahmed-building-9404569.html",
                            Name = " DARWISH BIN AHMED BUILDING,",
                            Occupancy = 4,
                            Rate = 0.0,
                            Sqft = 950,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
